<a href="https://colab.research.google.com/github/dineshRaja29/Pytorch-Tutorials/blob/main/AutoGradIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Autograd is PyTorch’s automatic differentiation engine that powers neural network training

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Fri May  7 01:22:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)

In [ ]:
print(a, b)

tensor([5.], requires_grad=True) tensor([6.], requires_grad=True)


In [ ]:
y = a**3  + b**2

In [ ]:
y 

tensor([161.], grad_fn=<AddBackward0>)

In [ ]:
# dy/da = 3 * a**2 = 75 (here a = 5)
# dy/db = 2 * b = 12 (here b = 6)

In [ ]:
print("a's gradient is ", a.grad)
print("b's gradient is ", b.grad)

a's gradient is  None
b's gradient is  None


In [ ]:
# computing the derivatives 
y.backward()

In [ ]:
print("a's gradient is ", a.grad)
print("b's gradient is ", b.grad)

a's gradient is  tensor([75.])
b's gradient is  tensor([12.])


Affine Transformation Computation

In [ ]:
W = torch.randn(10, 1, requires_grad = True)
b = torch.randn(1, requires_grad = True)

In [ ]:
print(W.shape)
print(b.shape)

torch.Size([10, 1])
torch.Size([1])


In [ ]:
# Features
x = torch.rand(1,10)

In [ ]:
output = torch.matmul(x, W) + b

In [ ]:
loss = 1 - output

In [ ]:
loss

tensor([[-2.0104]], grad_fn=<RsubBackward1>)

In [ ]:
output

tensor([[-0.0012]], grad_fn=<AddBackward0>)

In [ ]:
print(W.grad)
print(b.grad)

None
None


In [ ]:
print(W)
print(b)

tensor([[ 2.7879],
        [ 0.4570],
        [ 1.8832],
        [ 0.9923],
        [ 1.5021],
        [-1.2023],
        [ 0.6798],
        [-1.3896],
        [-0.8273],
        [ 0.9807]], requires_grad=True)
tensor([-1.7052], requires_grad=True)


In [ ]:
loss.backward()

In [ ]:
print(W.grad)
print(b.grad)

tensor([[-0.4567],
        [-0.4051],
        [-0.7959],
        [-0.2295],
        [-0.9231],
        [-0.5401],
        [-0.4505],
        [-0.0258],
        [-0.0263],
        [-0.5558]])
tensor([-1.])


In [ ]:
print(W.grad, '\n==\n', W )

tensor([[-0.4567],
        [-0.4051],
        [-0.7959],
        [-0.2295],
        [-0.9231],
        [-0.5401],
        [-0.4505],
        [-0.0258],
        [-0.0263],
        [-0.5558]]) 
==
 tensor([[ 2.7879],
        [ 0.4570],
        [ 1.8832],
        [ 0.9923],
        [ 1.5021],
        [-1.2023],
        [ 0.6798],
        [-1.3896],
        [-0.8273],
        [ 0.9807]], requires_grad=True)


In [ ]:
learning_rate = 0.01
with torch.no_grad():
  W = W - learning_rate * W.grad.data

In [ ]:
W

tensor([[ 2.7924],
        [ 0.4611],
        [ 1.8912],
        [ 0.9946],
        [ 1.5114],
        [-1.1969],
        [ 0.6843],
        [-1.3894],
        [-0.8270],
        [ 0.9863]])