<a href="https://colab.research.google.com/github/dineshRaja29/Pytorch-Tutorials/blob/main/BasicPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
import numpy as np

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Wed May  5 03:09:04 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
data = [[1,2],[3,4]]

In [ ]:
np.array(data)

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(data)

array([[1, 2],
       [3, 4]])

In [ ]:
#Random numpy array
numpy_data = np.random.rand(3,4)

In [ ]:
torch.tensor(numpy_data)

tensor([[0.3060, 0.6919, 0.7376, 0.9899],
        [0.7308, 0.1870, 0.7346, 0.7970],
        [0.6855, 0.8838, 0.2334, 0.8862]], dtype=torch.float64)

In [ ]:
(torch.tensor(numpy_data).dtype)

torch.float64

In [ ]:
torch.from_numpy(numpy_data)

tensor([[0.3060, 0.6919, 0.7376, 0.9899],
        [0.7308, 0.1870, 0.7346, 0.7970],
        [0.6855, 0.8838, 0.2334, 0.8862]], dtype=torch.float64)

In [ ]:
# Alternative way to conver the numpy to torch tensor
torch.tensor(numpy_data)


tensor([[0.3060, 0.6919, 0.7376, 0.9899],
        [0.7308, 0.1870, 0.7346, 0.7970],
        [0.6855, 0.8838, 0.2334, 0.8862]], dtype=torch.float64)

In [ ]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch_tensor = torch.rand(3,4)

In [ ]:
torch_tensor.dtype

torch.float32

In [ ]:
torch_tensor.device

device(type='cpu')

In [ ]:
torch_tensor.to("cuda") # not inplace

tensor([[0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532]], device='cuda:0')

In [ ]:
torch_tensor.device 

device(type='cpu')

In [ ]:
torch_tensor = torch_tensor.to("cuda")

In [ ]:
torch_tensor 

tensor([[0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532]], device='cuda:0')

In [ ]:
torch_tensor[:, 2:3]

tensor([[0.8401],
        [0.6271],
        [0.7586]], device='cuda:0')

In [ ]:
torch_tensor.mul(torch_tensor)

tensor([[0.0567, 0.1407, 0.7058, 0.1588],
        [0.1219, 0.5045, 0.3933, 0.0706],
        [0.1566, 0.0251, 0.5755, 0.3061]], device='cuda:0')

In [ ]:
torch_tensor * torch_tensor

tensor([[0.0567, 0.1407, 0.7058, 0.1588],
        [0.1219, 0.5045, 0.3933, 0.0706],
        [0.1566, 0.0251, 0.5755, 0.3061]], device='cuda:0')

In [ ]:
torch_tensor.matmul(torch_tensor.T)

tensor([[1.0619, 0.9822, 1.0114],
        [0.9822, 1.0903, 0.8735],
        [1.0114, 0.8735, 1.0633]], device='cuda:0')

In [ ]:
# Alternative way


torch.matmul(torch_tensor, torch_tensor.T)

tensor([[1.0619, 0.9822, 1.0114],
        [0.9822, 1.0903, 0.8735],
        [1.0114, 0.8735, 1.0633]], device='cuda:0')

In [ ]:
# Alternative way

torch_tensor @ torch_tensor.T

tensor([[1.0619, 0.9822, 1.0114],
        [0.9822, 1.0903, 0.8735],
        [1.0114, 0.8735, 1.0633]], device='cuda:0')

In [ ]:
print(torch_tensor.sum())
print(torch_tensor.max())
print(torch_tensor.min())

tensor(5.6700, device='cuda:0')
tensor(0.8401, device='cuda:0')
tensor(0.1585, device='cuda:0')


In [ ]:
torch.cat([torch_tensor, torch_tensor])

tensor([[0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532],
        [0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532]], device='cuda:0')

In [ ]:
torch.cat([torch_tensor, torch_tensor], axis = 1 )

tensor([[0.2380, 0.3750, 0.8401, 0.3985, 0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657, 0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532, 0.3958, 0.1585, 0.7586, 0.5532]],
       device='cuda:0')

In [ ]:
#Alternative is dim = 1
torch.cat([torch_tensor, torch_tensor], dim = 1)

tensor([[0.2380, 0.3750, 0.8401, 0.3985, 0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657, 0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532, 0.3958, 0.1585, 0.7586, 0.5532]],
       device='cuda:0')

In [ ]:
torch.nn.functional.softmax(torch_tensor)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0.1943, 0.2228, 0.3548, 0.2281],
        [0.2139, 0.3069, 0.2824, 0.1968],
        [0.2274, 0.1794, 0.3269, 0.2662]], device='cuda:0')

In [ ]:
torch.nn.functional.softmax(torch_tensor, dim = 0)

tensor([[0.3041, 0.3122, 0.3663, 0.3286],
        [0.3398, 0.4365, 0.2960, 0.2878],
        [0.3561, 0.2514, 0.3376, 0.3836]], device='cuda:0')

In [ ]:
torch_tensor.shape

torch.Size([3, 4])

In [ ]:
torch_tensor.size()

torch.Size([3, 4])

In [ ]:
torch_tensor.size(1)

4

In [ ]:
# Image dimension creation
torch.rand(10,3,128,128)

tensor([[[[0.4971, 0.5962, 0.0571,  ..., 0.0322, 0.8934, 0.2214],
          [0.8879, 0.0377, 0.7615,  ..., 0.3782, 0.8022, 0.4499],
          [0.3598, 0.5198, 0.4043,  ..., 0.1457, 0.8989, 0.3394],
          ...,
          [0.7420, 0.5485, 0.6576,  ..., 0.6297, 0.7343, 0.3742],
          [0.9223, 0.7391, 0.1430,  ..., 0.0036, 0.6811, 0.0370],
          [0.3976, 0.9447, 0.9706,  ..., 0.8072, 0.6361, 0.5321]],

         [[0.0220, 0.3578, 0.6086,  ..., 0.0270, 0.9571, 0.5105],
          [0.6440, 0.9449, 0.0240,  ..., 0.2725, 0.7386, 0.4533],
          [0.3006, 0.2337, 0.5264,  ..., 0.6468, 0.4545, 0.2624],
          ...,
          [0.6250, 0.6501, 0.8009,  ..., 0.1951, 0.2987, 0.1585],
          [0.6484, 0.2208, 0.1682,  ..., 0.8462, 0.9522, 0.1883],
          [0.4931, 0.9462, 0.2201,  ..., 0.9976, 0.7900, 0.9560]],

         [[0.6345, 0.7882, 0.3472,  ..., 0.2265, 0.6195, 0.3940],
          [0.7601, 0.1893, 0.4721,  ..., 0.8064, 0.8568, 0.7347],
          [0.3608, 0.4621, 0.7637,  ..., 0

In [ ]:
torch.rand(10, 3, 128, 128).size()

torch.Size([10, 3, 128, 128])

In [ ]:
#clipping the values

torch_tensor.clip(0.2, 0.8)

tensor([[0.2380, 0.3750, 0.8000, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.2000, 0.7586, 0.5532]], device='cuda:0')

In [ ]:
torch_tensor

tensor([[0.2380, 0.3750, 0.8401, 0.3985],
        [0.3492, 0.7103, 0.6271, 0.2657],
        [0.3958, 0.1585, 0.7586, 0.5532]], device='cuda:0')

In [ ]:
torch_tensor.cpu().detach().numpy()

array([[0.23802811, 0.37503916, 0.8401201 , 0.39847136],
       [0.34916306, 0.7103001 , 0.6271087 , 0.26570898],
       [0.39575607, 0.15845478, 0.7586075 , 0.55324113]], dtype=float32)